repos:
  - repo: https://github.com/dotnet/format
    rev: "v5.1.225507"  # Specify a tag or sha here, or run "pre-commit autoupdate"
    hooks:
      - id: dotnet-format
        name: dotnet format
        language: dotnet
        types_or: ['c#', 'vb']
        entry: dotnet-format --include --fix-whitespace
    - repo: https://github.com/prettier/prettier
    rev: <versÃ£o_desejada>
    hooks:
      - id: prettier
        name: Prettier
        types:
          - c#
          - vb
        entry: prettier --check
